### ISSUE TITLE
.pyc is checked in

### ISSUE THREAD

**Issue by jim-bo** [dfci/cidc-ingestion-api#101]
Should be no .pyc checked into the repo. please remove.

![image](https://user-images.githubusercontent.com/317043/48778095-52095300-eca2-11e8-9994-40e83ef41a5d.png)

**Comment by lemccarthy** [comment]
Fixed as of: https://github.com/dfci/cidc-ingestion-api/commit/aac381b9ad410a3a5e0d5baf6086f30b2bc2e1b9

close on next PR including this commit.
