### ISSUE TITLE
olink values are rounded

### ISSUE THREAD

**Issue by jim-bo** [dfci/cidc-ingestion-api#85]
Need to support the full floating point value.

![image](https://user-images.githubusercontent.com/317043/46548423-09860980-c89d-11e8-91d4-be55eae0fd4b.png)

**Comment by jim-bo** [comment]
Was this ever fixed @lemccarthy

**Comment by lemccarthy** [comment]
@jim-bo Yes, I'm fairly certain it was, most probably in this: https://github.com/dfci/cidc-ingestion-api/commit/180e5eedd164d4327eebb286caa083dfd532fa50 merge to master. We can test to make double sure if you want.
